### PR TITLE
Module #2 Understand how to use variables, functions, and packages

### PR DESCRIPTION
**Pull request by chrismld**
Content ready for module "Understand how to use variables, functions, and packages"

### CODE REVIEW

**Comment by meaghanlewis** [comment]
Reviewing this today @christianhxc! Sorry for the delay

**Comment by chrismld** [comment]
no worries @meaghanlewis I just wasn't sure if you received a notification when I created the PR :)

**Comment by meaghanlewis** [comment]
Module 2 looks great! I like all the code examples and the explanations and resources that you link to.

A couple changes for this module:
- could you be more clear about whether learners should be trying out the code examples or not. As i started going through unit 1 on variables, I wasn't sure initially if I should just read along or follow along in VS Code or the Go Playground. You do a great job of calling this out in units 2, 3, and 4 because you say things like: "Run the following code snippet..." and "Run the code..."
  - maybe just add that something at the beginning of unit 1 that says "Run the code examples in VS Code or the Go Playground yourself" or something similar
- Challenges (like in unit 2 and 4) need to have a solution after them for learners to reference and check their answer (even if it seems really simple)

A couple notes to keep in mind for the future (I went ahead and made these changes for module 2):
- code blocks should specify the language to use. Like this:
Screen Shot 2020-11-25 at 9 34 50 AM
- bullets should use `-` instead of `*`

**Comment by chrismld** [comment]
@meaghanlewis got it, I'll make those changes then ... thanks for taking care of the other ones you mentioned :)

**Comment by chrismld** [comment]
@meaghanlewis changes are done, please review and let me know :)

**Review by meaghanlewis — APPROVED** [review]
Thanks @christianhxc looks great to me!

**Pull request merged**
